name: transenv
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20210324.2=hd77b12b_0
  - absl-py=0.15.0=pyhd3eb1b0_0
  - aiohttp=3.8.1=py39h2bbff1b_1
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow-cpp=3.0.0=py39haed7efe_4_cpu
  - astor=0.8.1=py39haa95532_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.1=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - aws-c-cal=0.4.5=hffb5579_7
  - aws-c-common=0.5.1=h2bbff1b_0
  - aws-c-event-stream=0.2.7=h141f785_0
  - aws-c-io=0.9.0=hc33d8df_1
  - aws-checksums=0.1.11=hc33d8df_2
  - aws-sdk-cpp=1.8.138=hac61a3b_3
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py39haa95532_0
  - boost-cpp=1.73.0=h2bbff1b_11
  - bottleneck=1.3.4=py39h080aedc_0
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - bzip2=1.0.8=he774522_0
  - c-ares=1.18.1=h2bbff1b_0
  - ca-certificates=2022.6.15=h5b45459_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2022.6.15=py39hcbf5309_0
  - cffi=1.15.0=py39h2bbff1b_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py39haa95532_0
  - cloudpickle=2.1.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cryptography=3.4.8=py39h71e12ea_0
  - cudatoolkit=11.3.1=h59b6b97_2
  - dataclasses=0.8=pyh6d0b6a4_7
  - datasets=1.18.3=py_0
  - debugpy=1.5.1=py39hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dill=0.3.4=pyhd3eb1b0_0
  - entrypoints=0.3=py39haa95532_0
  - filelock=3.6.0=pyhd3eb1b0_0
  - flatbuffers=2.0.0=h6c2663c_0
  - freetype=2.10.4=hd328e21_0
  - frozenlist=1.2.0=py39h2bbff1b_0
  - fsspec=2022.2.0=pyhd3eb1b0_0
  - gast=0.4.0=pyhd3eb1b0_0
  - gflags=2.2.2=ha925a31_0
  - giflib=5.2.1=h62dcd97_0
  - glog=0.4.0=h33f27b4_0
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpc-cpp=1.35.0=hc60d5dd_4
  - grpcio=1.42.0=py39hc60d5dd_0
  - h5py=3.6.0=py39h3de5c98_0
  - hdf5=1.10.6=h7ebc959_0
  - huggingface_hub=0.2.1=pyhd3eb1b0_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=68.1=h6c2663c_0
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.8.2=py39haa95532_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.4.1=py39haa95532_1
  - ipython=7.31.1=py39haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py39haa95532_1
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h2bbff1b_0
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_core=4.9.2=py39haa95532_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - libboost=1.73.0=h6c2663c_11
  - libcurl=7.80.0=h86230a5_0
  - libevent=2.1.12=hcc03200_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.14.0=h23ce68f_0
  - libssh2=1.9.0=h7a1dbc1_1
  - libthrift=0.13.0=he1d8c1a_6
  - libtiff=4.2.0=hd0e1b90_0
  - libutf8proc=2.6.1=h2bbff1b_0
  - libuv=1.40.0=he774522_0
  - libwebp=1.2.2=h2bbff1b_0
  - lz4-c=1.9.3=h2bbff1b_1
  - markdown=3.3.4=py39haa95532_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.1=py39h277e83a_0
  - mkl_random=1.2.2=py39hf11a4ad_0
  - multidict=5.1.0=py39h2bbff1b_2
  - multiprocess=0.70.12.2=py39h2bbff1b_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - numexpr=2.8.1=py39hb80d3ca_0
  - numpy=1.21.5=py39ha4e8547_0
  - numpy-base=1.21.5=py39hc2deb75_0
  - oauthlib=3.2.0=pyhd3eb1b0_0
  - openssl=1.1.1p=h8ffe710_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.5=py39h6214cd6_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py39hdc2b20a_0
  - pip=21.2.4=py39haa95532_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - protobuf=3.14.0=py39hd77b12b_1
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyjwt=2.1.0=py39haa95532_0
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyreadline=2.1=py39haa95532_1
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.7=h6244533_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-flatbuffers=1.12=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py39h2bbff1b_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.2=py3.9_cuda11.3_cudnn8_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - pywin32=302=py39h827c3e9_1
  - pyzmq=22.3.0=py39hd77b12b_2
  - re2=2020.11.01=hd77b12b_1
  - regex=2021.8.3=py39h2bbff1b_0
  - requests=2.27.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - sacremoses=0.0.43=pyhd3eb1b0_0
  - scipy=1.7.3=py39h0a974cb_0
  - setuptools=58.0.4=py39haa95532_0
  - shap=0.41.0=py39h2e25243_0
  - six=1.16.0=pyhd3eb1b0_1
  - slicer=0.0.7=pyhd8ed1ab_0
  - snappy=1.1.8=h33f27b4_0
  - sqlite=3.38.0=h2bbff1b_0
  - tbb=2021.5.0=h2d74725_1
  - tensorboard-data-server=0.6.0=py39haa95532_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.6.0=mkl_py39h31650da_0
  - tensorflow-base=2.6.0=mkl_py39h9201259_0
  - tensorflow-estimator=2.6.0=pyh7b7c402_0
  - termcolor=1.1.0=py39haa95532_1
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11=h2bbff1b_0
  - tokenizers=0.10.3=py39h8c9392a_1
  - torchaudio=0.10.2=py39_cu113
  - torchvision=0.11.3=py39_cu113
  - tornado=6.1=py39h2bbff1b_0
  - tqdm=4.63.0=pyhd3eb1b0_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - transformers=4.16.2=pyhd8ed1ab_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2021e=hda174b7_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=2.0.3=pyhd3eb1b0_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - wincertstore=0.2=py39haa95532_2
  - wrapt=1.13.3=py39h2bbff1b_2
  - xxhash=0.8.0=h2bbff1b_3
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - yarl=1.6.3=py39h2bbff1b_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=hbd8134f_5
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - beautifulsoup4==4.11.1
    - bertviz==1.4.0
    - bleach==5.0.0
    - boto3==1.24.24
    - botocore==1.27.24
    - captum==0.5.0
    - csscompressor==0.9.5
    - cycler==0.11.0
    - daiquiri==3.0.1
    - defusedxml==0.7.1
    - ecco==0.1.2
    - fastjsonschema==2.15.3
    - fonttools==4.33.3
    - imageio==2.19.0
    - jinja2==3.1.2
    - jmespath==1.0.1
    - jsonschema==4.5.1
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-datatables==0.3.9
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - jupyter-nbutils==0.1.3
    - jupyter-require==0.6.1
    - jupyterlab-pygments==0.2.2
    - keras==2.8.0
    - keras-applications==1.0.8
    - kiwisolver==1.4.2
    - libclang==13.0.0
    - lime==0.2.0.1
    - llvmlite==0.38.1
    - lxml==4.8.0
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - mistune==0.8.4
    - nbclient==0.6.3
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - networkx==2.8
    - notebook==6.4.11
    - numba==0.55.2
    - pandocfilters==1.5.0
    - prometheus-client==0.14.1
    - pyarrow==3.0.0
    - pyrsistent==0.18.1
    - python-json-logger==2.0.2
    - pywavelets==1.3.0
    - pywinpty==2.0.5
    - pyyaml==5.4.1
    - s3transfer==0.6.0
    - scikit-image==0.19.2
    - scikit-learn==0.24.2
    - seaborn==0.11.2
    - send2trash==1.8.0
    - sentencepiece==0.1.96
    - soupsieve==2.3.2.post1
    - tensorboard==2.8.0
    - tensorflow-io-gcs-filesystem==0.24.0
    - terminado==0.15.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - tifffile==2022.4.28
    - tinycss2==1.1.1
    - webencodings==0.5.1
prefix: C:\Users\ivank\anaconda3\envs\transenv
